use sea_orm_migration::prelude::*;

/// CRYP-ENC-004(b) / CRYP-2FA-002 / CRYP-ENC-013 / CRYP-ENC-004(a).
///
/// Adds the NOT NULL `session_auth_secret` column (a server-random per-user
/// secret that the session auth hash is derived from, replacing the raw-email
/// basis) and backfills a random value for every existing user, plus a runbook
/// for the at-rest encryption of `google_id` and `two_fa_secret`.
///
/// ── (b) session_auth_secret ────────────────────────────────────────────────
///
/// The session auth hash was previously derived from the user's email (for
/// OAuth users without a password). Email is a poor secret: it is known to the
/// IdP, visible in DB dumps, and changes rarely. This adds a dedicated 64-hex
/// (256-bit) per-user secret, backfilled to a CSPRNG value for every existing
/// row at migration time, so the hash becomes unpredictable even if the email
/// is known. `services/auth.rs` reads this column via `Model::session_auth_secret`
/// instead of `email`.
///
/// The backfill default uses `gen_random_uuid()` (built into Postgres 13+, no
/// extension) — two UUIDs (256 bits concatenated) per row, so existing sessions
/// are implicitly invalidated (their snapshot hash no longer matches) and every
/// user gets a fresh, unpredictable secret. NEW rows get a secret generated by
/// the application (`ActiveModelBehavior::before_save`) when the service layer
/// does not supply one.
///
/// ── google_id / two_fa_secret re-encryption runbook ──────────────────────
///
/// `google_id` and `two_fa_secret` are stored at rest as field-crypto envelopes
/// from this migration onward (`D1:` / `V1:` tags; see
/// `src/utils/field_crypto.rs` and `src/db/sea_models/user/model.rs`). The
/// application layer is fully backward-compatible:
///
///   * Reads: `Model::google_id_plain()` / `two_fa_secret_plain()` detect an
///     envelope and decrypt; a legacy plaintext value is returned AS-IS so a
///     half-migrated DB keeps working (TOTP verify / OAuth lookup succeed).
///   * Writes: `ActiveModelBehavior::before_save` encrypts any plaintext value
///     it sees; an already-encrypted envelope is passed through (idempotent).
///   * `find_by_google_id` encrypts the lookup key and matches the stored
///     ciphertext column.
///
/// This means NO row-level backfill is required for correctness — but a DB
/// still holding plaintext google_ids is NOT searchable via the encrypted
/// lookup until those rows are re-encrypted. To backfill in place, run once
/// with `FIELD_ENC_KEY` in the process env:
///
/// ```sh
/// # From backend/api (loads each user, re-saves so before_save re-encrypts):
/// FIELD_ENC_KEY=<32-byte key> cargo run --features full \
///     --bin ruxlog-backfill-user-field-crypto
/// ```
///
/// (The bundled helper `ruxlog-backfill-user-field-crypto` does exactly this:
/// load each row via `Entity::find()`, set `google_id`/`two_fa_secret` to the
/// decrypted PLAINTEXT, and `ActiveModel.update()` — `before_save` re-encrypts
/// under the current key.) If existing plaintext rows are dev/test data, a hard
/// clobber is
/// also valid:
/// ```sql
/// UPDATE users SET two_fa_secret = NULL WHERE two_fa_secret IS NOT NULL;
/// UPDATE users SET google_id    = NULL WHERE google_id    IS NOT NULL;
/// ```
#[derive(DeriveMigrationName)]
pub struct Migration;

#[derive(Iden)]
enum Users {
    Table,
    SessionAuthSecret,
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Forward-only: add the NOT NULL session_auth_secret column with a
        // CSPRNG-random default expression so the backfill is atomic with the
        // ALTER (every existing row gets a distinct 64-hex value in one DDL).
        // `gen_random_uuid()` is built into Postgres 13+; concatenating two
        // UUIDs (with the dashes stripped) yields 256 bits of randomness.
        //
        // We then DROP the default so future INSERTs do NOT silently rely on a
        // SQL-side value — the application (`before_save`) generates the secret
        // explicitly, which keeps the key/secret boundary in one place.
        manager
            .get_connection()
            .execute_unprepared(
                r#"ALTER TABLE users
                     ADD COLUMN session_auth_secret TEXT NOT NULL
                     DEFAULT (replace(gen_random_uuid()::text, '-', '')
                           || replace(gen_random_uuid()::text, '-', ''));"#,
            )
            .await?;

        manager
            .get_connection()
            .execute_unprepared(
                r#"ALTER TABLE users ALTER COLUMN session_auth_secret DROP DEFAULT;"#,
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Forward-only convention. Dropping the column would invalidate every
        // existing session (the hash reverts to the email basis); reverting is
        // therefore a destructive op left to the operator, not the migration.
        manager
            .alter_table(
                Table::alter()
                    .table(Users::Table)
                    .drop_column(Users::SessionAuthSecret)
                    .to_owned(),
            )
            .await
    }
}
