//! Build script: ensure `assets/editor.bundle.js` exists before compile.
//!
//! Dioxus 0.8's `asset!` macro validates that the referenced asset file exists
//! at compile time (0.7 resolved it lazily). `editor.bundle.js` is a generated,
//! gitignored artifact built from `assets/editor/index.ts` via `bun run
//! editor:build` (see package.json). Without this script, a bare `cargo check`
//! — including in CI, which does not run the JS toolchain — fails on the
//! `asset!("/assets/editor.bundle.js")` site in `editor_js_host.rs`.
//!
//! Behavior:
//! - If the bundle already exists and is newer than `index.ts`, do nothing
//!   (fast path; the dev rebuilds via `just admin editor:build` / `editor:watch`).
//! - Else, if `bun` and `node_modules/` are available, run `bun run editor:build`
//!   to (re)generate the real bundle (no network: only when deps are installed).
//! - Else, write a minimal stub so `asset!` resolves. The editor will be
//!   non-functional in that build (acceptable for `cargo check` / CI without the
//!   JS toolchain); run the editor build to get the real bundle.

use std::path::Path;
use std::process::Command;
use std::time::SystemTime;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let root = Path::new(&manifest_dir);
    let assets_dir = root.join("assets");
    let bundle = assets_dir.join("editor.bundle.js");
    let index_ts = assets_dir.join("editor").join("index.ts");

    // Rerun when the editor TS source changes (so a dev edit triggers a rebuild).
    if index_ts.exists() {
        println!("cargo:rerun-if-changed={}", index_ts.display());
    }

    let mtime = |p: &Path| {
        std::fs::metadata(p)
            .and_then(|m| m.modified())
            .unwrap_or(SystemTime::UNIX_EPOCH)
    };

    let present = bundle.exists();
    let stale = index_ts.exists() && present && mtime(&index_ts) > mtime(&bundle);
    if present && !stale {
        return; // Nothing to do — bundle is present and fresh.
    }

    // Only attempt a real build when the JS toolchain is already set up (avoids
    // any network/install step inside `cargo check`).
    let can_build = root.join("node_modules").exists()
        && Command::new("bun")
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);

    let built = if can_build {
        Command::new("bun")
            .args(["run", "editor:build"])
            .current_dir(root)
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
    } else {
        false
    };

    if !built && !bundle.exists() {
        // Stub so the 0.8 `asset!` macro finds a file. Real bundle is built by
        // `bun run editor:build` in the dev workflow.
        let _ = std::fs::write(
            &bundle,
            "/* editor.bundle.js stub (generated by build.rs): bun unavailable. \
             Run `bun run editor:build` to build the real editor bundle. */\n",
        );
        println!("cargo:warning=editor.bundle.js stub written (bun/node_modules unavailable); the editor will not function until `bun run editor:build` is run");
    }
}
